controller_list:
  - name: fake_arm_controller
    type: $(arg execution_type)
    joints:
      - base_joint
      - rev_joint1
      - rev_joint2
initial:  # Define initial robot poses.
  - group: arm
    pose: home