controller_list:
  - name: fake_arm_controller
    type: $(arg execution_type)
    joints:
      - num_piston_joint
      - mid_link_joint
      - end_link_joint
initial:  # Define initial robot poses.
  - group: arm
    pose: home