arm:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Position Controllers ---------------------------------------
  num_base_joint_position_controller:
    type: position_controllers/JointPositionController
    joint: num_base_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  num_piston_joint_position_controller:
    type: position_controllers/JointPositionController
    joint: num_piston_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  mid_link_joint_position_controller:
    type: position_controllers/JointPositionController
    joint: mid_link_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  end_link_joint_position_controller:
    type: position_controllers/JointPositionController
    joint: end_link_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
